### 1
### 中铝报表接口：订单进度查询
GET {{baseUrl}}zlreport/order/progress?form_id=1240468533985546242&condition={}&page_number=1&page_size=1000
Accept: */*
Cache-Control: no-cache
tenant_id: 1218734876489027584
grant_id: 1239814084715745280
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
###

### 2
### 中铝报表接口：铸轧生产产量
GET {{baseUrl}}zlreport/data/list/zhuzha?form_id=1240468533985546252&condition={}&page_num=1&page_size=1000
Accept: */*
Cache-Control: no-cache
tenant_id: 1218734876489027584
grant_id: 1239814084715745280
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
###

### 3
### 中铝报表接口：冷轧生产产量
GET {{baseUrl}}zlreport/data/list/lengzha?form_id=1240468533985546251&condition={}&page_num=1&page_size=1000
Accept: */*
Cache-Control: no-cache
tenant_id: 1218734876489027584
grant_id: 1239814084715745280
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
###

### 4
### 中铝报表接口：在制品情况查询汇总
GET {{baseUrl}}/zlreport/data/productionvolumequerysummary?form_id=1240468533985546249
Accept: */*
Cache-Control: no-cache
tenant_id: 1218734876489027584
grant_id: 1239814084715745280
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
###

### 5
### 中铝报表接口：在制金属盘点(有问题)
GET {{baseUrl}}zlreport/scm/inProcessMetalInventory?form_id=1240468533985546246&conditions={}&page_num=1&page_size=1000
Accept: */*
Cache-Control: no-cache
tenant_id: 1218734876489027584
grant_id: 1239814084715745280
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3R5cGUiOiJwaG9uZSIsImV4cCI6MTU3MzE4NDQ1NCwiaWF0IjoxNTczMTgyNjU0LCJpZCI6MTE2MTkyMDAyODc5NTM0Mjg0MCwiaWRlbnRpZmllciI6IjEzNzk0MzkxMzg2IiwiaXNzIjoic2NtIiwibmFtZSI6IuiDoea4hea1qSIsInRlbmFudF9pZCI6MTE1NjQ0Nzk1Mjk5NTIyNTYwMH0.f33facd5e25d4415dbee0426a1796f9312f9028221d56a35e1746c9cb90defef
###

### 6
### 中铝报表接口：中通华提供给nc的接口,生产产量查询汇总报表。
GET http://222.85.133.211:30088/api/zlreport/data/list/report?condition={"select_time":"1585670400000-1590854400000"}
###